version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./postgres:/data/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin      
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: z-help
    restart: always